=== VanitasQQ/Lineage2-Server-Interlude/game/data/stats/armor/armors.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
  L2J XML armors DTD

  This defines a simple and consistent way of creating a namespace
  of armors objects, managed by L2J

  Each "item" element in this document defines a armor item.

  XML documents that conform to this DTD should declare the following doctype:

  <!DOCTYPE list SYSTEM "armors.dtd">
-->

<!--
  The document root. A document can contain item definitions only.
-->
<!ELEMENT list (item)*>


<!--
  The document item. A item can contain "for, add, sub, div or mul" element.
  add, sub, div and mul can modify a stat
-->
<!ELEMENT item (for|add|sub|div|mul)*>

<!--
  The document for. A item can contain "add,mull,enchant,sub and div" element
-->
<!ELEMENT for (add|mul|enchant|sub|div)*>


<!--
  add, div, sub, mul could coutain condition "and" and "or"
-->
<!ELEMENT add (and|or)*>
<!ELEMENT div (and|or)*>
<!ELEMENT sub (and|or)*>
<!ELEMENT mul (and|or)*>

<!--
  enchant are empty
-->
<!ELEMENT enchant EMPTY>

<!--
  and conditions could specified use of an item or his kind, the target or a not condition
-->
<!ELEMENT and (using|target|not)*>
<!--
  the "not" condition could specified the use of an item
-->
<!ELEMENT not (using)*>
<!--
  the "or" could specified several "and" condition
-->
<!ELEMENT or (and)*>
<!--
  target specified the type of the target (dagger ?)
-->
<!ELEMENT target EMPTY>

<!--
  using specified the item, the position on paperdoll and the level of enchant
  (should used three attributes instead of one...)
-->
<!ELEMENT using EMPTY>

<!--
 id and name are mandatory for an item
-->
<!ATTLIST item id CDATA #REQUIRED>
<!ATTLIST item name CDATA #REQUIRED>

<!--
 all operations must specified val order and stat
-->
<!ATTLIST add val CDATA #REQUIRED>
<!ATTLIST add order CDATA #REQUIRED>
<!ATTLIST add stat CDATA #REQUIRED>

<!ATTLIST div val CDATA #REQUIRED>
<!ATTLIST div order CDATA #IMPLIED>
<!ATTLIST div stat CDATA #REQUIRED>

<!ATTLIST sub val CDATA #REQUIRED>
<!ATTLIST sub order CDATA #IMPLIED>
<!ATTLIST sub stat CDATA #REQUIRED>

<!ATTLIST mul val CDATA #REQUIRED>
<!ATTLIST mul order CDATA #IMPLIED>
<!ATTLIST mul stat CDATA #REQUIRED>

<!ATTLIST enchant val CDATA #REQUIRED>
<!ATTLIST enchant order CDATA #IMPLIED>
<!ATTLIST enchant stat CDATA #REQUIRED>

<!--
 the use of an item could be specified for a kind of item or a dependency with another item
-->
<!ATTLIST using slotitem CDATA #IMPLIED>
<!ATTLIST using kind CDATA #IMPLIED>

<!--

-->
<!ATTLIST target using CDATA #IMPLIED>

=== VanitasQQ/Lineage2-Server-Interlude/game/data/stats/armor/9800-9899.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "armors.dtd">
<list>
<item id='9820' name="Shadow Item: Clan Oath Helm">
  <for>
    <add val='37' order='0x10' stat='pDef'/>
  </for>
</item>
<item id='9821' name="Shadow Item: Clan Oath Armor">
  <for>
    <add val='158' order='0x10' stat='pDef'/>
  </for>
</item>
<item id='9822' name="Shadow Item: Clan Oath Gauntlets - Heavy Armor">
  <for>
    <add val='24' order='0x10' stat='pDef'/>
  </for>
</item>
<item id='9823' name="Shadow Item: Clan Oath Sabaton - Heavy Armor">
  <for>
    <add val='24' order='0x10' stat='pDef'/>
  </for>
</item>
<item id='9824' name="Shadow Item: Clan Oath Brigandine">
  <for>
    <add val='119' order='0x10' stat='pDef'/>
  </for>
</item>
<item id='9825' name="Shadow Item: Clan Oath Leather Gloves - Light Armor">
  <for>
    <add val='24' order='0x10' stat='pDef'/>
  </for>
</item>
<item id='9826' name="Shadow Item: Clan Oath Boots - Light Armor">
  <for>
    <add val='24' order='0x10' stat='pDef'/>
  </for>
</item>
<item id='9827' name="Shadow Item: Clan Oath Aketon">
  <for>
    <add val='79' order='0x10' stat='pDef'/>
    <add val='239' order='0x40' stat='maxMp'/>
  </for>
</item>
<item id='9828' name="Shadow Item: Clan Oath Padded Gloves - Robe">
  <for>
    <add val='24' order='0x10' stat='pDef'/>
  </for>
</item>
<item id='9829' name="Shadow Item: Clan Oath Sandals - Robe">
  <for>
    <add val='24' order='0x10' stat='pDef'/>
  </for>
</item>
<item id='9830' name="Improved Apella Helm">
  <cond msgId="1518">
    <player pledgeClass="5"/>
  </cond>
  <for>
    <add val='73' order='0x10' stat='pDef'/>
    <enchant val='0' order='0x0C' stat='pDef'/>
  </for>
</item>
<item id='9831' name="Improved Apella Plate Armor">
  <cond msgId="1518">
    <player pledgeClass="5"/>
  </cond>
  <for>
    <add val='293' order='0x10' stat='pDef'/>
    <enchant val='0' order='0x0C' stat='pDef'/>
  </for>
</item>
<item id='9832' name="Improved Apella Gauntlet - Heavy Armor">
  <cond msgId="1518">
    <player pledgeClass="5"/>
  </cond>
  <for>
    <add val='49' order='0x10' stat='pDef'/>
    <enchant val='0' order='0x0C' stat='pDef'/>
  </for>
</item>
<item id='9833' name="Improved Apella Solleret - Heavy Armor">
  <cond msgId="1518">
    <player pledgeClass="5"/>
  </cond>
  <for>
    <add val='49' order='0x10' stat='pDef'/>
    <enchant val='0' order='0x0C' stat='pDef'/>
  </for>
</item>
<item id='9834' name="Improved Apella Brigandine">
  <cond msgId="1518">
    <player pledgeClass="5"/>
  </cond>
  <for>
    <add val='220' order='0x10' stat='pDef'/>
    <enchant val='0' order='0x0C' stat='pDef'/>
  </for>
</item>
<item id='9835' name="Improved Apella Leather Gloves - Light Armor">
  <cond msgId="1518">
    <player pledgeClass="5"/>
  </cond>
  <for>
    <add val='49' order='0x10' stat='pDef'/>
    <enchant val='0' order='0x0C' stat='pDef'/>
  </for>
</item>
<item id='9836' name="Improved Apella Boots - Light Armor">
  <cond msgId="1518">
    <player pledgeClass="5"/>
  </cond>
  <for>
    <add val='49' order='0x10' stat='pDef'/>
    <enchant val='0' order='0x0C' stat='pDef'/>
  </for>
</item>
<item id='9837' name="Improved Apella Doublet">
  <cond msgId="1518">
    <player pledgeClass="5"/>
  </cond>
  <for>
    <add val='147' order='0x10' stat='pDef'/>
    <add val='718' order='0x40' stat='maxMp'/>
    <enchant val='0' order='0x0C' stat='pDef'/>
  </for>
</item>
<item id='9838' name="Improved Apella Silk Gloves - Robe">
  <cond msgId="1518">
    <player pledgeClass="5"/>
  </cond>
  <for>
    <add val='49' order='0x10' stat='pDef'/>
    <enchant val='0' order='0x0C' stat='pDef'/>
  </for>
</item>
<item id='9839' name="Improved Apella Sandals - Robe">
  <cond msgId="1518">
    <player pledgeClass="5"/>
  </cond>
  <for>
    <add val='49' order='0x10' stat='pDef'/>
    <enchant val='0' order='0x0C' stat='pDef'/>
  </for>
</item>
<item id='9883' name="Teddy Bear Hat - Big Head">
  <for>
  </for>
</item>
<item id='9884' name="Piggy Hat - Big Head">
  <for>
  </for>
</item>
<item id='9885' name="Jester Hat - Big Head">
  <for>
  </for>
</item>
<item id='9886' name="Wizard Hat - Big Head">
  <for>
  </for>
</item>
<item id='9887' name="Dapper Cap - Big Head">
  <for>
  </for>
</item>
<item id='9888' name="Romantic Chapeau - Big Head">
  <for>
  </for>
</item>
<item id='9889' name="Iron Circlet - Big Head">
  <for>
  </for>
</item>
<item id='9890' name="Teddy Bear Hat - Firework">
  <for>
  </for>
</item>
<item id='9891' name="Piggy Hat - Firework">
  <for>
  </for>
</item>
<item id='9892' name="Jester Hat - Firework">
  <for>
  </for>
</item>
<item id='9893' name="Wizard Hat - Firework">
  <for>
  </for>
</item>
<item id='9894' name="Dapper Cap - Firework">
  <for>
  </for>
</item>
<item id='9895' name="Romantic Chapeau - Firework">
  <for>
  </for>
</item>
<item id='9896' name="Iron Circlet - Firework">
  <for>
  </for>
</item>
<item id='9899' name="Weight Loss Ring">
  <for>
  </for>
</item>
</list>
