=== VanitasQQ/Lineage2-Server-Interlude/game/data/stats/armor/armors.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
  L2J XML armors DTD

  This defines a simple and consistent way of creating a namespace
  of armors objects, managed by L2J

  Each "item" element in this document defines a armor item.

  XML documents that conform to this DTD should declare the following doctype:

  <!DOCTYPE list SYSTEM "armors.dtd">
-->

<!--
  The document root. A document can contain item definitions only.
-->
<!ELEMENT list (item)*>


<!--
  The document item. A item can contain "for, add, sub, div or mul" element.
  add, sub, div and mul can modify a stat
-->
<!ELEMENT item (for|add|sub|div|mul)*>

<!--
  The document for. A item can contain "add,mull,enchant,sub and div" element
-->
<!ELEMENT for (add|mul|enchant|sub|div)*>


<!--
  add, div, sub, mul could coutain condition "and" and "or"
-->
<!ELEMENT add (and|or)*>
<!ELEMENT div (and|or)*>
<!ELEMENT sub (and|or)*>
<!ELEMENT mul (and|or)*>

<!--
  enchant are empty
-->
<!ELEMENT enchant EMPTY>

<!--
  and conditions could specified use of an item or his kind, the target or a not condition
-->
<!ELEMENT and (using|target|not)*>
<!--
  the "not" condition could specified the use of an item
-->
<!ELEMENT not (using)*>
<!--
  the "or" could specified several "and" condition
-->
<!ELEMENT or (and)*>
<!--
  target specified the type of the target (dagger ?)
-->
<!ELEMENT target EMPTY>

<!--
  using specified the item, the position on paperdoll and the level of enchant
  (should used three attributes instead of one...)
-->
<!ELEMENT using EMPTY>

<!--
 id and name are mandatory for an item
-->
<!ATTLIST item id CDATA #REQUIRED>
<!ATTLIST item name CDATA #REQUIRED>

<!--
 all operations must specified val order and stat
-->
<!ATTLIST add val CDATA #REQUIRED>
<!ATTLIST add order CDATA #REQUIRED>
<!ATTLIST add stat CDATA #REQUIRED>

<!ATTLIST div val CDATA #REQUIRED>
<!ATTLIST div order CDATA #IMPLIED>
<!ATTLIST div stat CDATA #REQUIRED>

<!ATTLIST sub val CDATA #REQUIRED>
<!ATTLIST sub order CDATA #IMPLIED>
<!ATTLIST sub stat CDATA #REQUIRED>

<!ATTLIST mul val CDATA #REQUIRED>
<!ATTLIST mul order CDATA #IMPLIED>
<!ATTLIST mul stat CDATA #REQUIRED>

<!ATTLIST enchant val CDATA #REQUIRED>
<!ATTLIST enchant order CDATA #IMPLIED>
<!ATTLIST enchant stat CDATA #REQUIRED>

<!--
 the use of an item could be specified for a kind of item or a dependency with another item
-->
<!ATTLIST using slotitem CDATA #IMPLIED>
<!ATTLIST using kind CDATA #IMPLIED>

<!--

-->
<!ATTLIST target using CDATA #IMPLIED>

=== VanitasQQ/Lineage2-Server-Interlude/game/data/stats/armor/9500-9599.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "armors.dtd">
<list>
<item id='9514' name="Sealed Dynasty Breast Plate">
  <for>
    <add val='214' order='0x10' stat='pDef'/>
    <enchant val='0' order='0x0C' stat='pDef'/>
  </for>
</item>
<item id='9515' name="Sealed Dynasty Gaiter">
  <for>
    <add val='134' order='0x10' stat='pDef'/>
    <enchant val='0' order='0x0C' stat='pDef'/>
  </for>
</item>
<item id='9516' name="Sealed Dynasty Helmet">
  <for>
    <add val='92' order='0x10' stat='pDef'/>
    <enchant val='0' order='0x0C' stat='pDef'/>
  </for>
</item>
<item id='9517' name="Sealed Dynasty Gauntlets">
  <for>
    <add val='61' order='0x10' stat='pDef'/>
    <enchant val='0' order='0x0C' stat='pDef'/>
  </for>
</item>
<item id='9518' name="Sealed Dynasty Boots">
  <for>
    <add val='61' order='0x10' stat='pDef'/>
    <enchant val='0' order='0x0C' stat='pDef'/>
  </for>
</item>
<item id='9519' name="Sealed Dynasty Leather Armor">
  <for>
    <add val='161' order='0x10' stat='pDef'/>
    <enchant val='0' order='0x0C' stat='pDef'/>
  </for>
</item>
<item id='9520' name="Sealed Dynasty Leather Leggings">
  <for>
    <add val='100' order='0x10' stat='pDef'/>
    <enchant val='0' order='0x0C' stat='pDef'/>
  </for>
</item>
<item id='9521' name="Sealed Dynasty Leather Helmet">
  <for>
    <add val='92' order='0x10' stat='pDef'/>
    <enchant val='0' order='0x0C' stat='pDef'/>
  </for>
</item>
<item id='9522' name="Sealed Dynasty Leather Gloves">
  <for>
    <add val='61' order='0x10' stat='pDef'/>
    <enchant val='0' order='0x0C' stat='pDef'/>
  </for>
</item>
<item id='9523' name="Sealed Dynasty Leather Boots">
  <for>
    <add val='61' order='0x10' stat='pDef'/>
    <enchant val='0' order='0x0C' stat='pDef'/>
  </for>
</item>
<item id='9524' name="Sealed Dynasty Tunic">
  <for>
    <add val='107' order='0x10' stat='pDef'/>
    <add val='592' order='0x40' stat='maxMp'/>
    <enchant val='0' order='0x0C' stat='pDef'/>
  </for>
</item>
<item id='9525' name="Sealed Dynasty Stockings">
  <for>
    <add val='67' order='0x10' stat='pDef'/>
    <add val='370' order='0x40' stat='maxMp'/>
    <enchant val='0' order='0x0C' stat='pDef'/>
  </for>
</item>
<item id='9526' name="Sealed Dynasty Circlet">
  <for>
    <add val='92' order='0x10' stat='pDef'/>
    <enchant val='0' order='0x0C' stat='pDef'/>
  </for>
</item>
<item id='9527' name="Sealed Dynasty Gloves">
  <for>
    <add val='61' order='0x10' stat='pDef'/>
    <enchant val='0' order='0x0C' stat='pDef'/>
  </for>
</item>
<item id='9528' name="Sealed Dynasty Shoes">
  <for>
    <add val='61' order='0x10' stat='pDef'/>
    <enchant val='0' order='0x0C' stat='pDef'/>
  </for>
</item>
<item id='9577' name="Cotton Shirt">
  <for>
    <add val='6' order='0x10' stat='pDef'/>
    <enchant val='0' order='0x0C' stat='pDef'/>
  </for>
</item>
<item id='9578' name="Linen Shirt">
  <for>
    <add val='12' order='0x10' stat='pDef'/>
    <enchant val='0' order='0x0C' stat='pDef'/>
  </for>
</item>
<item id='9579' name="Silk Shirt">
  <for>
    <add val='17' order='0x10' stat='pDef'/>
    <enchant val='0' order='0x0C' stat='pDef'/>
  </for>
</item>
<item id='9580' name="Thin Leather Shirt">
  <for>
    <add val='21' order='0x10' stat='pDef'/>
    <enchant val='0' order='0x0C' stat='pDef'/>
  </for>
</item>
<item id='9581' name="Scale Shirt">
  <for>
    <add val='23' order='0x10' stat='pDef'/>
    <enchant val='0' order='0x0C' stat='pDef'/>
  </for>
</item>
<item id='9582' name="Mithril Shirt">
  <for>
    <add val='28' order='0x10' stat='pDef'/>
    <enchant val='0' order='0x0C' stat='pDef'/>
  </for>
</item>
<item id='9583' name="Striped Cotton Shirt">
  <for>
    <add val='8' order='0x10' stat='pDef'/>
    <enchant val='0' order='0x0C' stat='pDef'/>
  </for>
</item>
<item id='9584' name="Striped Linen Shirt">
  <for>
    <add val='14' order='0x10' stat='pDef'/>
    <enchant val='0' order='0x0C' stat='pDef'/>
  </for>
</item>
<item id='9585' name="Striped Silk Shirt">
  <for>
    <add val='19' order='0x10' stat='pDef'/>
    <enchant val='0' order='0x0C' stat='pDef'/>
  </for>
</item>
<item id='9586' name="Striped Thin Leather Shirt">
  <for>
    <add val='22' order='0x10' stat='pDef'/>
    <enchant val='0' order='0x0C' stat='pDef'/>
  </for>
</item>
<item id='9587' name="Striped Scale Shirt">
  <for>
    <add val='26' order='0x10' stat='pDef'/>
    <enchant val='0' order='0x0C' stat='pDef'/>
  </for>
</item>
<item id='9588' name="Striped Mithril Shirt">
  <for>
    <add val='30' order='0x10' stat='pDef'/>
    <enchant val='0' order='0x0C' stat='pDef'/>
  </for>
</item>
<item id='9589' name="Iron Bracelet">
  <for>
    <set val='1' order='0x50' stat='talisman'/>
  </for>
</item>
<item id='9590' name="Bronze Bracelet">
  <for>
    <set val='2' order='0x50' stat='talisman'/>
  </for>
</item>
<item id='9591' name="Steel Bracelet">
  <for>
    <set val='3' order='0x50' stat='talisman'/>
  </for>
</item>
<item id='9592' name="Mithril Bracelet">
  <for>
    <set val='4' order='0x50' stat='talisman'/>
  </for>
</item>
</list>

=== VanitasQQ/Lineage2-Server-Interlude/game/data/stats/armor/9200-9299.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "armors.dtd">
<list>
<item id='9200' name="Shadow Item - Jester Hat - Firework">
  <for>
    <add val='0' order='0x10' stat='pDef'/>
  </for>
</item>
<item id='9201' name="Shadow Item - Wizard Hat - Firework">
  <for>
    <add val='0' order='0x10' stat='pDef'/>
  </for>
</item>
<item id='9202' name="Shadow Item - Dapper Cap - Firework">
  <for>
    <add val='0' order='0x10' stat='pDef'/>
  </for>
</item>
<item id='9203' name="Shadow Item - Romantic Chapeau - Firework">
  <for>
    <add val='0' order='0x10' stat='pDef'/>
  </for>
</item>
<item id='9204' name="Shadow Item - Iron Circlet - Firework">
  <for>
    <add val='0' order='0x10' stat='pDef'/>
  </for>
</item>
<item id='9208' name="Phantom Mask (Event)">
  <for>
    <add val='0' order='0x10' stat='pDef'/>
  </for>
</item>
</list>

=== VanitasQQ/Lineage2-Server-Interlude/game/data/stats/armor/7800-7899.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "armors.dtd">
<list>
<item id='7836' name="Santa's Hat">
  <for>
    <add val='0' order='0x10' stat='pDef'/>
  </for>
</item>
<item id='7837' name="Sayha's White Mask">
  <for>
    <add val='0' order='0x10' stat='pDef'/>
  </for>
</item>
<item id='7839' name="Gran Kain's Black Mask">
  <for>
    <add val='0' order='0x10' stat='pDef'/>
  </for>
</item>
<item id='7840' name="Rabbit Ears (Event)">
  <for>
    <add val='0' order='0x10' stat='pDef'/>
  </for>
</item>
<item id='7841' name="Racoon Ears (Event)">
  <for>
    <add val='0' order='0x10' stat='pDef'/>
  </for>
</item>
<item id='7842' name="Cat Ears (Event)">
  <for>
    <add val='0' order='0x10' stat='pDef'/>
  </for>
</item>
<item id='7843' name="Pirate's Eyepatch (Event)">
  <for>
    <add val='0' order='0x10' stat='pDef'/>
  </for>
</item>
<item id='7844' name="Monocle (Event)">
  <for>
    <add val='0' order='0x10' stat='pDef'/>
  </for>
</item>
<item id='7845' name="Outlaw's Eyepatch (Event)">
  <for>
    <add val='0' order='0x10' stat='pDef'/>
  </for>
</item>
<item id='7846' name="Lady's Hairpin (Event)">
  <cond msgId="1518">
    <player sex="1"/>
  </cond>
  <for>
    <add val='0' order='0x10' stat='pDef'/>
  </for>
</item>
<item id='7847' name="Noblewoman's Hairpin (Event)">
  <cond msgId="1518">
    <player sex="1"/>
  </cond>
  <for>
    <add val='0' order='0x10' stat='pDef'/>
  </for>
</item>
<item id='7848' name="Forget-me-not Hairpin (Event)">
  <cond msgId="1518">
    <player sex="1"/>
  </cond>
  <for>
    <add val='0' order='0x10' stat='pDef'/>
  </for>
</item>
<item id='7849' name="Daisy Hairpin (Event)">
  <cond msgId="1518">
    <player sex="1"/>
  </cond>
  <for>
    <add val='0' order='0x10' stat='pDef'/>
  </for>
</item>
<item id='7850' name="Clan Oath Helm">
  <cond msgId="1518">
    <player pledgeClass="1"/>
  </cond>
  <for>
    <add val='37' order='0x10' stat='pDef'/>
    <enchant val='0' order='0x0C' stat='pDef'/>
  </for>
</item>
<item id='7851' name="Clan Oath Armor">
  <cond msgId="1518">
    <player pledgeClass="1"/>
  </cond>
  <for>
    <add val='158' order='0x10' stat='pDef'/>
    <enchant val='0' order='0x0C' stat='pDef'/>
  </for>
</item>
<item id='7852' name="Clan Oath Gauntlets - Heavy Armor">
  <cond msgId="1518">
    <player pledgeClass="1"/>
  </cond>
  <for>
    <add val='24' order='0x10' stat='pDef'/>
    <enchant val='0' order='0x0C' stat='pDef'/>
  </for>
</item>
<item id='7853' name="Clan Oath Sabaton - Heavy Armor">
  <cond msgId="1518">
    <player pledgeClass="1"/>
  </cond>
  <for>
    <add val='24' order='0x10' stat='pDef'/>
    <enchant val='0' order='0x0C' stat='pDef'/>
  </for>
</item>
<item id='7854' name="Clan Oath Brigandine">
  <cond msgId="1518">
    <player pledgeClass="1"/>
  </cond>
  <for>
    <add val='119' order='0x10' stat='pDef'/>
    <enchant val='0' order='0x0C' stat='pDef'/>
  </for>
</item>
<item id='7855' name="Clan Oath Leather Gloves - Light Armor">
  <cond msgId="1518">
    <player pledgeClass="1"/>
  </cond>
  <for>
    <add val='24' order='0x10' stat='pDef'/>
    <enchant val='0' order='0x0C' stat='pDef'/>
  </for>
</item>
<item id='7856' name="Clan Oath Boots - Light Armor">
  <cond msgId="1518">
    <player pledgeClass="1"/>
  </cond>
  <for>
    <add val='24' order='0x10' stat='pDef'/>
    <enchant val='0' order='0x0C' stat='pDef'/>
  </for>
</item>
<item id='7857' name="Clan Oath Aketon">
  <cond msgId="1518">
    <player pledgeClass="1"/>
  </cond>
  <for>
    <add val='79' order='0x10' stat='pDef'/>
    <add val='239' order='0x40' stat='maxMp'/>
    <enchant val='0' order='0x0C' stat='pDef'/>
  </for>
</item>
<item id='7858' name="Clan Oath Padded Gloves - Robe">
  <cond msgId="1518">
    <player pledgeClass="1"/>
  </cond>
  <for>
    <add val='24' order='0x10' stat='pDef'/>
    <enchant val='0' order='0x0C' stat='pDef'/>
  </for>
</item>
<item id='7859' name="Clan Oath Sandals - Robe">
  <cond msgId="1518">
    <player pledgeClass="1"/>
  </cond>
  <for>
    <add val='24' order='0x10' stat='pDef'/>
    <enchant val='0' order='0x0C' stat='pDef'/>
  </for>
</item>
<item id='7860' name="Apella Helm">
  <for>
    <add val='69' order='0x10' stat='pDef'/>
    <enchant val='0' order='0x0C' stat='pDef'/>
  </for>
</item>
<item id='7861' name="Apella Plate Armor">
  <for>
    <add val='278' order='0x10' stat='pDef'/>
    <enchant val='0' order='0x0C' stat='pDef'/>
  </for>
</item>
<item id='7862' name="Apella Gauntlet - Heavy Armor">
  <for>
    <add val='46' order='0x10' stat='pDef'/>
    <enchant val='0' order='0x0C' stat='pDef'/>
  </for>
</item>
<item id='7863' name="Apella Solleret - Heavy Armor">
  <for>
    <add val='46' order='0x10' stat='pDef'/>
    <enchant val='0' order='0x0C' stat='pDef'/>
  </for>
</item>
<item id='7864' name="Apella Brigandine">
  <for>
    <add val='209' order='0x10' stat='pDef'/>
    <enchant val='0' order='0x0C' stat='pDef'/>
  </for>
</item>
<item id='7865' name="Apella Leather Gloves - Light Armor">
  <for>
    <add val='46' order='0x10' stat='pDef'/>
    <enchant val='0' order='0x0C' stat='pDef'/>
  </for>
</item>
<item id='7866' name="Apella Boots - Light Armor">
  <for>
    <add val='46' order='0x10' stat='pDef'/>
    <enchant val='0' order='0x0C' stat='pDef'/>
  </for>
</item>
<item id='7867' name="Apella Doublet">
  <for>
    <add val='139' order='0x10' stat='pDef'/>
    <add val='665' order='0x40' stat='maxMp'/>
    <enchant val='0' order='0x0C' stat='pDef'/>
  </for>
</item>
<item id='7868' name="Apella Silk Gloves - Robe">
  <for>
    <add val='46' order='0x10' stat='pDef'/>
    <enchant val='0' order='0x0C' stat='pDef'/>
  </for>
</item>
<item id='7869' name="Apella Sandals - Robe">
  <for>
    <add val='46' order='0x10' stat='pDef'/>
    <enchant val='0' order='0x0C' stat='pDef'/>
  </for>
</item>
<item id='7870' name="Sealed Apella Helmet">
  <for>
    <add val='69' order='0x10' stat='pDef'/>
    <enchant val='0' order='0x0C' stat='pDef'/>
  </for>
</item>
<item id='7871' name="Sealed Apella Plate Armor">
  <for>
    <add val='278' order='0x10' stat='pDef'/>
    <enchant val='0' order='0x0C' stat='pDef'/>
  </for>
</item>
<item id='7872' name="Sealed Apella Gauntlet - Heavy Armor">
  <for>
    <add val='46' order='0x10' stat='pDef'/>
    <enchant val='0' order='0x0C' stat='pDef'/>
  </for>
</item>
<item id='7873' name="Sealed Apella Solleret - Heavy Armor">
  <for>
    <add val='46' order='0x10' stat='pDef'/>
    <enchant val='0' order='0x0C' stat='pDef'/>
  </for>
</item>
<item id='7874' name="Sealed Apella Brigandine">
  <for>
    <add val='209' order='0x10' stat='pDef'/>
    <enchant val='0' order='0x0C' stat='pDef'/>
  </for>
</item>
<item id='7875' name="Sealed Apella Leather Gloves - Light Armor">
  <for>
    <add val='46' order='0x10' stat='pDef'/>
    <enchant val='0' order='0x0C' stat='pDef'/>
  </for>
</item>
<item id='7876' name="Sealed Apella Boots - Light Armor">
  <for>
    <add val='46' order='0x10' stat='pDef'/>
    <enchant val='0' order='0x0C' stat='pDef'/>
  </for>
</item>
<item id='7877' name="Sealed Apella Doublet">
  <for>
    <add val='139' order='0x10' stat='pDef'/>
    <add val='665' order='0x40' stat='maxMp'/>
    <enchant val='0' order='0x0C' stat='pDef'/>
  </for>
</item>
<item id='7878' name="Sealed Apella Silk Gloves - Robe">
  <for>
    <add val='46' order='0x10' stat='pDef'/>
    <enchant val='0' order='0x0C' stat='pDef'/>
  </for>
</item>
<item id='7879' name="Sealed Apella Sandals - Robe">
  <for>
    <add val='46' order='0x10' stat='pDef'/>
    <enchant val='0' order='0x0C' stat='pDef'/>
  </for>
</item>
</list>

=== VanitasQQ/Lineage2-Server-Interlude/game/data/stats/armor/9100-9199.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "armors.dtd">
<list>
<item id='9100' name="Shadow Item: Magestic Boots">
  <for>
    <add val='49' order='0x10' stat='pDef'/>
    <enchant val='0' order='0x0C' stat='pDef'/>
  </for>
</item>
<item id='9101' name="Shadow Item: Majestic Robe">
  <for>
    <add val='147' order='0x10' stat='pDef'/>
    <add val='718' order='0x40' stat='maxMp'/>
    <enchant val='0' order='0x0C' stat='pDef'/>
  </for>
</item>
<item id='9102' name="Shadow Item: Magestic Gauntlet">
  <for>
    <add val='49' order='0x10' stat='pDef'/>
    <enchant val='0' order='0x0C' stat='pDef'/>
  </for>
</item>
<item id='9103' name="Shadow Item: Magestic Boots">
  <for>
    <add val='49' order='0x10' stat='pDef'/>
    <enchant val='0' order='0x0C' stat='pDef'/>
  </for>
</item>
<item id='9128' name="Shadow Item: Mithril Gauntlet">
  <for>
    <add val='36' order='0x10' stat='pDef'/>
    <enchant val='0' order='0x0C' stat='pDef'/>
  </for>
</item>
<item id='9138' name="Santa's Hat">
  <for>
    <add val='0' order='0x10' stat='pDef'/>
  </for>
</item>
<item id='9145' name="Little Angel Wings (Event)">
  <for>
    <add val='0' order='0x10' stat='pDef'/>
  </for>
</item>
<item id='9158' name="Golden Circlet of Redemption">
  <for>
    <add val='0' order='0x10' stat='pDef'/>
  </for>
</item>
<item id='9159' name="Silver Circlet of Salvation">
  <for>
    <add val='0' order='0x10' stat='pDef'/>
  </for>
</item>
<item id='9160' name="Pig Wrangler's Cap">
  <for>
    <add val='0' order='0x10' stat='pDef'/>
  </for>
</item>
<item id='9177' name="Shadow Item - Teddy Bear Hat - Resurrection">
  <for>
    <add val='0' order='0x10' stat='pDef'/>
  </for>
</item>
<item id='9178' name="Shadow Item - Piggy Hat - Resurrection">
  <for>
    <add val='0' order='0x10' stat='pDef'/>
  </for>
</item>
<item id='9179' name="Shadow Item - Jester Hat - Resurrection">
  <for>
    <add val='0' order='0x10' stat='pDef'/>
  </for>
</item>
<item id='9180' name="Shadow Item - Wizard Hat - Resurrection">
  <for>
    <add val='0' order='0x10' stat='pDef'/>
  </for>
</item>
<item id='9181' name="Shadow Item - Dapper Cap - Resurrection">
  <for>
    <add val='0' order='0x10' stat='pDef'/>
  </for>
</item>
<item id='9182' name="Shadow Item - Romantic Chapeau - Resurrection">
  <for>
    <add val='0' order='0x10' stat='pDef'/>
  </for>
</item>
<item id='9183' name="Shadow Item - Iron Circlet - Resurrection">
  <for>
    <add val='0' order='0x10' stat='pDef'/>
  </for>
</item>
<item id='9184' name="Shadow Item - Teddy Bear Hat - Escape">
  <for>
    <add val='0' order='0x10' stat='pDef'/>
  </for>
</item>
<item id='9185' name="Shadow Item - Piggy Hat - Escape">
  <for>
    <add val='0' order='0x10' stat='pDef'/>
  </for>
</item>
<item id='9186' name="Shadow Item - Jester Hat - Escap">
  <for>
    <add val='0' order='0x10' stat='pDef'/>
  </for>
</item>
<item id='9187' name="Shadow Item - Wizard Hat - Escape">
  <for>
    <add val='0' order='0x10' stat='pDef'/>
  </for>
</item>
<item id='9188' name="Shadow Item - Dapper Cap - Escap">
  <for>
    <add val='0' order='0x10' stat='pDef'/>
  </for>
</item>
<item id='9189' name="Shadow Item - Romantic Chapeau - Escape">
  <for>
    <add val='0' order='0x10' stat='pDef'/>
  </for>
</item>
<item id='9190' name="Shadow Item - Iron Circlet - Escap">
  <for>
    <add val='0' order='0x10' stat='pDef'/>
  </for>
</item>
<item id='9191' name="Shadow Item - Teddy Bear Hat - Big Head">
  <for>
    <add val='0' order='0x10' stat='pDef'/>
  </for>
</item>
<item id='9192' name="Shadow Item - Piggy Hat - Big Head">
  <for>
    <add val='0' order='0x10' stat='pDef'/>
  </for>
</item>
<item id='9193' name="Shadow Item - Jester Hat - Big Head">
  <for>
    <add val='0' order='0x10' stat='pDef'/>
  </for>
</item>
<item id='9194' name="Shadow Item - Wizard Hat - Big Head">
  <for>
    <add val='0' order='0x10' stat='pDef'/>
  </for>
</item>
<item id='9195' name="Shadow Item - Dapper Cap - Big Head">
  <for>
    <add val='0' order='0x10' stat='pDef'/>
  </for>
</item>
<item id='9196' name="Shadow Item - Romantic Chapeau - Big Head">
  <for>
    <add val='0' order='0x10' stat='pDef'/>
  </for>
</item>
<item id='9197' name="Shadow Item - Iron Circlet - Big Head">
  <for>
    <add val='0' order='0x10' stat='pDef'/>
  </for>
</item>
<item id='9198' name="Shadow Item - Teddy Bear Hat - Firework">
  <for>
    <add val='0' order='0x10' stat='pDef'/>
  </for>
</item>
<item id='9199' name="Shadow Item - Piggy Hat - Firework">
  <for>
    <add val='0' order='0x10' stat='pDef'/>
  </for>
</item>
</list>

=== VanitasQQ/Lineage2-Server-Interlude/game/data/stats/armor/8500-8599.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "armors.dtd">
<list>
<item id='8541' name="Little Harness">
  <for>
    <add val='10' order='0x10' stat='mDef'/>
    <add val='25' order='0x10' stat='pDef'/>
  </for>
</item>
<item id='8552' name="Mask of Victory">
  <for>
    <add val='0' order='0x10' stat='pDef'/>
  </for>
</item>
<item id='8557' name="Blue Party Hat">
  <for>
    <add val='0' order='0x10' stat='pDef'/>
  </for>
</item>
<item id='8558' name="Eva's Mark (Event)">
  <for>
    <add val='0' order='0x10' stat='pDef'/>
  </for>
</item>
<item id='8559' name="Diadem">
  <cond msgId="1518">
    <player sex="1"/>
  </cond>
  <for>
    <add val='0' order='0x10' stat='pDef'/>
  </for>
</item>
<item id='8560' name="Bear Cap">
  <for>
    <add val='0' order='0x10' stat='pDef'/>
  </for>
</item>
<item id='8561' name="Pig Cap">
  <for>
    <add val='0' order='0x10' stat='pDef'/>
  </for>
</item>
<item id='8562' name="Jester Cap">
  <for>
    <add val='0' order='0x10' stat='pDef'/>
  </for>
</item>
<item id='8563' name="Wizard Hat">
  <for>
    <add val='0' order='0x10' stat='pDef'/>
  </for>
</item>
<item id='8564' name="Dandy Cap">
  <for>
    <add val='0' order='0x10' stat='pDef'/>
  </for>
</item>
<item id='8565' name="Romantic Chaperon">
  <for>
    <add val='0' order='0x10' stat='pDef'/>
  </for>
</item>
<item id='8566' name="Iron Circlet">
  <for>
    <add val='0' order='0x10' stat='pDef'/>
  </for>
</item>
<item id='8567' name="Valakas Slayer Circlet">
  <for>
    <add val='0' order='0x10' stat='pDef'/>
  </for>
</item>
<item id='8568' name="Antharas Slayer Circlet">
  <for>
    <add val='0' order='0x10' stat='pDef'/>
  </for>
</item>
<item id='8569' name="Half Face">
  <for>
    <add val='0' order='0x10' stat='pDef'/>
  </for>
</item>
</list>

=== VanitasQQ/Lineage2-Server-Interlude/game/data/stats/armor/9900-9999.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "armors.dtd">
<list>
<item id='9900' name="Quiet Footsteps Ring">
  <for>
  </for>
</item>
<item id='9909' name="Agathion Seal Bracelet">
  <for>
  </for>
</item>
<item id='9913' name="Talisman_Test">
  <for>
  </for>
</item>
<item id='9914' name="Blue Talisman of Power">
  <for>
  </for>
</item>
<item id='9915' name="Blue Talisman of Wild Magic">
  <for>
  </for>
</item>
<item id='9916' name="Blue Talisman of Defense">
  <for>
  </for>
</item>

<item id='9917' name="Red Talisman of Minimum Clarity">
  <for>
  </for>
</item>
<item id='9918' name="Red Talisman of Maximum Clarity">
  <for>
  </for>
</item>
<item id='9919' name="Blue Talisman of Reflection">
  <for>
  </for>
</item>
<item id='9920' name="Blue Talisman of Invisibility">
  <for>
  </for>
</item>
<item id='9921' name="Blue Talisman - Shield Protection">
  <for>
  </for>
</item>
<item id='9922' name="Black Talisman - Mending">
  <for>
  </for>
</item>
<item id='9923' name="Black Talisman - Escape">
  <for>
  </for>
</item>
<item id='9924' name="Blue Talisman of Healing">
  <for>
  </for>
</item>
<item id='9925' name="Red Talisman of Recovery">
  <for>
  </for>
</item>
<item id='9926' name="Blue Talisman of Defense">
  <for>
  </for>
</item>
<item id='9927' name="Blue Talisman of Magic Defense">
  <for>
  </for>
</item>
<item id='9928' name="Red Talisman of Mental Regeneration">
  <for>
  </for>
</item>
<item id='9929' name="Blue Talisman - Shield Protection">
  <for>
  </for>
</item>
<item id='9930' name="Blue Talisman of Evasion">
  <for>
  </for>
</item>
<item id='9931' name="Red Talisman of Meditation">
  <for>
  </for>
</item>
<item id='9932' name="Blue Talisman of Invincibility">
  <for>
  </for>
</item>
<item id='9933' name="Yellow Talisman of Power">
  <for>
  </for>
</item>
<item id='9934' name="Yellow Talisman of Violent Haste">
  <for>
  </for>
</item>
<item id='9935' name="Yellow Talisman of Arcane Defense">
  <for>
  </for>
</item>
<item id='9936' name="Yellow Talisman of Arcane Power">
  <for>
  </for>
</item>
<item id='9937' name="Yellow Talisman of Arcane Haste">
  <for>
  </for>
</item>
<item id='9938' name="Yellow Talisman of Accuracy">
  <for>
  </for>
</item>
<item id='9939' name="Yellow Talisman of Defense">
  <for>
  </for>
</item>
<item id='9940' name="Yellow Talisman of Alacrity">
  <for>
  </for>
</item>
<item id='9941' name="Yellow Talisman of Speed">
  <for>
  </for>
</item>
<item id='9942' name="Yellow Talisman of Critical Reduction">
  <for>
  </for>
</item>
<item id='9943' name="Yellow Talisman of Critical Power">
  <for>
  </for>
</item>
<item id='9944' name="Yellow Talisman of Critical Dodging">
  <for>
  </for>
</item>
<item id='9945' name="Yellow Talisman of Evasion">
  <for>
  </for>
</item>
<item id='9946' name="Yellow Talisman of Healing">
  <for>
  </for>
</item>
<item id='9947' name="Yellow Talisman of CP Regeneration">
  <for>
  </for>
</item>
<item id='9948' name="Yellow Talisman of Physical Regeneration">
  <for>
  </for>
</item>
<item id='9949' name="Yellow Talisman of Mental Regeneration">
  <for>
  </for>
</item>
<item id='9950' name="Grey Talisman of Weight Training">
  <for>
  </for>
</item>
<item id='9951' name="Grey Talisman of Mid-Grade Fishing">
  <for>
  </for>
</item>
<item id='9952' name="Orange Talisman - Hot Springs Recovery">
  <for>
  </for>
</item>
<item id='9953' name="Orange Talisman - Elixir of Life">
  <for>
  </for>
</item>
<item id='9954' name="Orange Talisman - Elixir of Mental Strength">
  <for>
  </for>
</item>
<item id='9955' name="Black Talisman of Vocalization">
  <for>
  </for>
</item>
<item id='9956' name="Black Talisman of Arcane Freedom">
  <for>
  </for>
</item>
<item id='9957' name="Black Talisman of Physical Freedom">
  <for>
  </for>
</item>
<item id='9958' name="Black Talisman of Rescue">
  <for>
  </for>
</item>
<item id='9959' name="Black Talisman of Free Speech">
  <for>
  </for>
</item>
<item id='9960' name="White Talisman of Bravery">
  <for>
  </for>
</item>
<item id='9961' name="White Talisman of Motion">
  <for>
  </for>
</item>
<item id='9962' name="White Talisman of Grounding">
  <for>
  </for>
</item>
<item id='9963' name="White Talisman of Attention">
  <for>
  </for>
</item>
<item id='9964' name="White Talisman of Bandages">
  <for>
  </for>
</item>
<item id='9965' name="White Talisman of Protection">
  <for>
  </for>
</item>
<item id='9966' name="White Talisman of Freedom">
  <for>
  </for>
</item>
</list>
